apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  labels:
    app: queue
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: fleetman-queue
          image: richardchesterwood/k8s-fleetman-queue:release2
          imagePullPolicy: Always
  selector:
    matchLabels:
      app: queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: fleetman-position-simulator
          image: richardchesterwood/k8s-fleetman-position-simulator:release2
          env:
            - name: SPRING_PROFILE_ACTIVE
              value: production-microservice
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  labels:
    app: tracker
spec:
  selector:
    matchLabels:
      app: tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
        - name: fleetman-position-tracker
          image: richardchesterwood/k8s-fleetman-position-tracker:release2
          env:
            - name: SPRING_PROFILE_ACTIVE
              value: production-microservice
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: fleetman-api-gateway
          image: richardchesterwood/k8s-fleetman-api-gateway:release2
          env:
            - name: SPRING_PROFILE_ACTIVE
              value: production-microservice
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: fleetman-webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release2
          env:
            - name: SPRING_PROFILE_ACTIVE
              value: production-microservice
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
spec:
  selector:
    app: queue
  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
      nodePort: 30012

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: tracker
    release:
  ports:
    - name: http
      port: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
    release:
  ports:
    - name: http
      port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
    release:
  ports:
    - name: http
      port: 8080
      nodePort: 30080
  type: NodePort