apiVersion : v1
kind: Pod
metadata:
  name: configmap-env-pod
spec:
  containers:
    - name: configmap-env-pod
      image: alpine
      command: ["sleep","3600"]
      env:
        - name: PLAYER_LIVES
          valueFrom:
            configMapKeyRef:
              name: player-pro-demo
              key: player_lives
        - name: PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: player-pro-demo
              key: properties_file_name
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: my-secret