apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistence-vol
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /vat/tmp