apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-writer
rules:
  - apiGroups: [""]
    verbs: ["get","watch","list","create","update","patch","delete"]
    resources: ["pods"]

  - apiGroups: [ "extensions","apps" ]
    verbs: [ "get","watch","list","create","update","patch","delete" ]
    resources: [ "deployments" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
  - kind: User
    name: edward
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-writer